// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";

function make(title, component) {
  return {
          title: title,
          component: component,
          excludeStories: new RegExp("\$\$[dD]efault|default|Default")
        };
}

var bsExports = ["$$default"];

function makeStory(args, component, param) {
  return Curry._1(component, args);
}

export {
  make ,
  bsExports ,
  makeStory ,
}
/* No side effect */
