// Generated by ReScript, PLEASE EDIT WITH CARE


function make(title, component) {
  return {
          title: title,
          component: component,
          excludeStories: new RegExp("\$\$[dD]efault|default|Default|.*Story")
        };
}

export {
  make ,
}
/* No side effect */
