// Generated by ReScript, PLEASE EDIT WITH CARE


var _map = {"PC":"PC","XL":"XL","LG":"LG","SM":"SM","XS":"XS"};

function sizeToJs(param) {
  return param;
}

function sizeFromJs(param) {
  return _map[param];
}

var ArrowDownLineBold = {};

var ArrowDownLineRegular = {};

var ArrowDownLineThin = {};

var ArrowLeftLineBold = {};

var ArrowLeftLineRegular = {};

var ArrowLeftLineThin = {};

var ArrowRightLineBold = {};

var ArrowRightLineRegular = {};

var ArrowRightLineThin = {};

var ArrowTriangleDownFill = {};

var ArrowTriangleDownLineBold = {};

var ArrowTriangleDownLineRegular = {};

var ArrowTriangleDownLineThin = {};

var ArrowTriangleUpFill = {};

var ArrowTriangleUpLineBold = {};

var ArrowTriangleUpLineRegular = {};

var ArrowTriangleUpLineThin = {};

var ArrowUpLineBold = {};

var ArrowUpLineRegular = {};

var ArrowUpLineThin = {};

var BookMarkFill = {};

var BookMarkLineBold = {};

var BookMarkLineRegular = {};

var BookMarkLineThin = {};

var CalendarFill = {};

var CalendarLineBold = {};

var CalendarLineRegular = {};

var CalendarLineThin = {};

var CameraFill = {};

var CameraLineBold = {};

var CameraLineRegular = {};

var CameraLineThin = {};

var CartFill = {};

var CartLineBold = {};

var CartLineRegular = {};

var CartLineThin = {};

var CertificationFill = {};

var CertificationLineBold = {};

var CertificationLineRegular = {};

var CertificationLineThin = {};

var ChatFill = {};

var ChatLineBold = {};

var ChatLineRegular = {};

var ChatLineThin = {};

var CheckCircleFill = {};

var CheckCircleLineBold = {};

var CheckCircleLineRegular = {};

var CheckCircleLineThin = {};

var CheckLineBold = {};

var CheckLineRegular = {};

var CheckLineThin = {};

var ChevronDownLineBold = {};

var ChevronDownLineRegular = {};

var ChevronDownLineThin = {};

var ChevronLeftLineBold = {};

var ChevronLeftLineRegular = {};

var ChevronLeftLineThin = {};

var ChevronRightLineBold = {};

var ChevronRightLineRegular = {};

var ChevronRightLineThin = {};

var ChevronUpLineBold = {};

var ChevronUpLineRegular = {};

var ChevronUpLineThin = {};

var ClockFill = {};

var ClockLineBold = {};

var ClockLineRegular = {};

var ClockLineThin = {};

var CloseLineBold = {};

var CloseLineRegular = {};

var CloseLineThin = {};

var CommentFill = {};

var CommentLineBold = {};

var CommentLineRegular = {};

var CommentLineThin = {};

var CompassFill = {};

var CompassLineBold = {};

var CompassLineRegular = {};

var CompassLineThin = {};

var CopyContentsFill = {};

var CopyContentsLineBold = {};

var CopyContentsLineRegular = {};

var CopyContentsLineThin = {};

var DeleteFill = {};

var DeleteLineBold = {};

var DeleteLineRegular = {};

var DeleteLineThin = {};

var DownloadFill = {};

var DownloadLineBold = {};

var DownloadLineRegular = {};

var DownloadLineThin = {};

var EditCutFill = {};

var EditCutLineBold = {};

var EditCutLineRegular = {};

var EditCutLineThin = {};

var EditFill = {};

var EditLineBold = {};

var EditLineRegular = {};

var EditLineThin = {};

var EyeFill = {};

var EyeLineBold = {};

var EyeLineRegular = {};

var EyeLineThin = {};

var EyeSlashFill = {};

var EyeSlashLineBold = {};

var EyeSlashLineRegular = {};

var EyeSlashLineThin = {};

var FarmFill = {};

var FarmLineBold = {};

var FarmLineRegular = {};

var FarmLineThin = {};

var HeartFill = {};

var HeartLineBold = {};

var HeartLineRegular = {};

var HeartLineThin = {};

var HelpFill = {};

var HelpLineBold = {};

var HelpLineRegular = {};

var HelpLineThin = {};

var HomeFill = {};

var HomeLineBold = {};

var HomeLineRegular = {};

var HomeLineThin = {};

var ImageFill = {};

var ImageLineBold = {};

var ImageLineRegular = {};

var ImageLineThin = {};

var InfoFill = {};

var InfoLineBold = {};

var InfoLineRegular = {};

var InfoLineThin = {};

var LinkClipLineBold = {};

var LinkClipLineRegular = {};

var LinkClipLineThin = {};

var LinkCopyLineBold = {};

var LinkCopyLineRegular = {};

var LinkCopyLineThin = {};

var LocationFill = {};

var LocationFill1 = {};

var LocationLineBold = {};

var LocationLineBold1 = {};

var LocationLineRegular = {};

var LocationLineRegular1 = {};

var LocationLineThin = {};

var LocationLineThin1 = {};

var MenuFill = {};

var MenuLineBold = {};

var MenuLineRegular = {};

var MenuLineThin = {};

var MicFill = {};

var MicLineBold = {};

var MicLineRegular = {};

var MicLineThin = {};

var MicSlashFill = {};

var MicSlashLineBold = {};

var MicSlashLineRegular = {};

var MicSlashLineThin = {};

var MinusLineBold = {};

var MinusLineRegular = {};

var MinusLineThin = {};

var MoneyBagFill = {};

var MoneyBagLineBold = {};

var MoneyBagLineRegular = {};

var MoneyBagLineThin = {};

var NoticeFill = {};

var NoticeLineBold = {};

var NoticeLineRegular = {};

var NoticeLineThin = {};

var NotificationFill = {};

var NotificationLineBold = {};

var NotificationLineRegular = {};

var NotificationLineThin = {};

var NotificationSlashFill = {};

var NotificationSlashLineBold = {};

var NotificationSlashLineRegular = {};

var NotificationSlashLineThin = {};

var PersonCircleFill = {};

var PersonCircleLineBold = {};

var PersonCircleLineRegular = {};

var PersonCircleLineThin = {};

var PersonFill = {};

var PersonLineBold = {};

var PersonLineRegular = {};

var PersonLineThin = {};

var PhoneFill = {};

var PhoneLineBold = {};

var PhoneLineRegular = {};

var PhoneLineThin = {};

var PinFill = {};

var PinLineBold = {};

var PinLineRegular = {};

var PinLineThin = {};

var PlayFill = {};

var PlayLineBold = {};

var PlayLineRegular = {};

var PlayLineThin = {};

var PlusCircleFill = {};

var PlusCircleLineBold = {};

var PlusCircleLineRegular = {};

var PlusCircleLineThin = {};

var PlusLineBold = {};

var PlusLineRegular = {};

var PlusLineThin = {};

var PostSquareFill = {};

var PostSquareLineBold = {};

var PostSquareLineRegular = {};

var PostSquareLineThin = {};

var RefreshLineBold = {};

var RefreshLineRegular = {};

var RefreshLineThin = {};

var SearchFill = {};

var SearchLineBold = {};

var SearchLineRegular = {};

var SearchLineThin = {};

var SeeMoreFill = {};

var SeeMoreLineBold = {};

var SeeMoreLineRegular = {};

var SeeMoreLineThin = {};

var SendPlaneFill = {};

var SendPlaneLineBold = {};

var SendPlaneLineRegular = {};

var SendPlaneLineThin = {};

var SettingFill = {};

var SettingLineBold = {};

var SettingLineRegular = {};

var SettingLineThin = {};

var ShareAndroidFill = {};

var ShareAndroidLineBold = {};

var ShareAndroidLineRegular = {};

var ShareAndroidLineThin = {};

var ShareArrowFill = {};

var ShareArrowLineBold = {};

var ShareArrowLineRegular = {};

var ShareArrowLineThin = {};

var ShareIosFill = {};

var ShareIosLineBold = {};

var ShareIosLineRegular = {};

var ShareIosLineThin = {};

var ThumbUpFill = {};

var ThumbUpLineBold = {};

var ThumbUpLineRegular = {};

var ThumbUpLineThin = {};

var TouchFill = {};

var TouchLineBold = {};

var TouchLineRegular = {};

var TouchLineThin = {};

var TrashFill = {};

var TrashLineBold = {};

var TrashLineRegular = {};

var TrashLineThin = {};

var VideoFill = {};

var VideoLineBold = {};

var VideoLineRegular = {};

var VideoLineThin = {};

var WebBold = {};

var WebFill = {};

var WebRegular = {};

var WebThin = {};

export {
  sizeToJs ,
  sizeFromJs ,
  ArrowDownLineBold ,
  ArrowDownLineRegular ,
  ArrowDownLineThin ,
  ArrowLeftLineBold ,
  ArrowLeftLineRegular ,
  ArrowLeftLineThin ,
  ArrowRightLineBold ,
  ArrowRightLineRegular ,
  ArrowRightLineThin ,
  ArrowTriangleDownFill ,
  ArrowTriangleDownLineBold ,
  ArrowTriangleDownLineRegular ,
  ArrowTriangleDownLineThin ,
  ArrowTriangleUpFill ,
  ArrowTriangleUpLineBold ,
  ArrowTriangleUpLineRegular ,
  ArrowTriangleUpLineThin ,
  ArrowUpLineBold ,
  ArrowUpLineRegular ,
  ArrowUpLineThin ,
  BookMarkFill ,
  BookMarkLineBold ,
  BookMarkLineRegular ,
  BookMarkLineThin ,
  CalendarFill ,
  CalendarLineBold ,
  CalendarLineRegular ,
  CalendarLineThin ,
  CameraFill ,
  CameraLineBold ,
  CameraLineRegular ,
  CameraLineThin ,
  CartFill ,
  CartLineBold ,
  CartLineRegular ,
  CartLineThin ,
  CertificationFill ,
  CertificationLineBold ,
  CertificationLineRegular ,
  CertificationLineThin ,
  ChatFill ,
  ChatLineBold ,
  ChatLineRegular ,
  ChatLineThin ,
  CheckCircleFill ,
  CheckCircleLineBold ,
  CheckCircleLineRegular ,
  CheckCircleLineThin ,
  CheckLineBold ,
  CheckLineRegular ,
  CheckLineThin ,
  ChevronDownLineBold ,
  ChevronDownLineRegular ,
  ChevronDownLineThin ,
  ChevronLeftLineBold ,
  ChevronLeftLineRegular ,
  ChevronLeftLineThin ,
  ChevronRightLineBold ,
  ChevronRightLineRegular ,
  ChevronRightLineThin ,
  ChevronUpLineBold ,
  ChevronUpLineRegular ,
  ChevronUpLineThin ,
  ClockFill ,
  ClockLineBold ,
  ClockLineRegular ,
  ClockLineThin ,
  CloseLineBold ,
  CloseLineRegular ,
  CloseLineThin ,
  CommentFill ,
  CommentLineBold ,
  CommentLineRegular ,
  CommentLineThin ,
  CompassFill ,
  CompassLineBold ,
  CompassLineRegular ,
  CompassLineThin ,
  CopyContentsFill ,
  CopyContentsLineBold ,
  CopyContentsLineRegular ,
  CopyContentsLineThin ,
  DeleteFill ,
  DeleteLineBold ,
  DeleteLineRegular ,
  DeleteLineThin ,
  DownloadFill ,
  DownloadLineBold ,
  DownloadLineRegular ,
  DownloadLineThin ,
  EditCutFill ,
  EditCutLineBold ,
  EditCutLineRegular ,
  EditCutLineThin ,
  EditFill ,
  EditLineBold ,
  EditLineRegular ,
  EditLineThin ,
  EyeFill ,
  EyeLineBold ,
  EyeLineRegular ,
  EyeLineThin ,
  EyeSlashFill ,
  EyeSlashLineBold ,
  EyeSlashLineRegular ,
  EyeSlashLineThin ,
  FarmFill ,
  FarmLineBold ,
  FarmLineRegular ,
  FarmLineThin ,
  HeartFill ,
  HeartLineBold ,
  HeartLineRegular ,
  HeartLineThin ,
  HelpFill ,
  HelpLineBold ,
  HelpLineRegular ,
  HelpLineThin ,
  HomeFill ,
  HomeLineBold ,
  HomeLineRegular ,
  HomeLineThin ,
  ImageFill ,
  ImageLineBold ,
  ImageLineRegular ,
  ImageLineThin ,
  InfoFill ,
  InfoLineBold ,
  InfoLineRegular ,
  InfoLineThin ,
  LinkClipLineBold ,
  LinkClipLineRegular ,
  LinkClipLineThin ,
  LinkCopyLineBold ,
  LinkCopyLineRegular ,
  LinkCopyLineThin ,
  LocationFill ,
  LocationFill1 ,
  LocationLineBold ,
  LocationLineBold1 ,
  LocationLineRegular ,
  LocationLineRegular1 ,
  LocationLineThin ,
  LocationLineThin1 ,
  MenuFill ,
  MenuLineBold ,
  MenuLineRegular ,
  MenuLineThin ,
  MicFill ,
  MicLineBold ,
  MicLineRegular ,
  MicLineThin ,
  MicSlashFill ,
  MicSlashLineBold ,
  MicSlashLineRegular ,
  MicSlashLineThin ,
  MinusLineBold ,
  MinusLineRegular ,
  MinusLineThin ,
  MoneyBagFill ,
  MoneyBagLineBold ,
  MoneyBagLineRegular ,
  MoneyBagLineThin ,
  NoticeFill ,
  NoticeLineBold ,
  NoticeLineRegular ,
  NoticeLineThin ,
  NotificationFill ,
  NotificationLineBold ,
  NotificationLineRegular ,
  NotificationLineThin ,
  NotificationSlashFill ,
  NotificationSlashLineBold ,
  NotificationSlashLineRegular ,
  NotificationSlashLineThin ,
  PersonCircleFill ,
  PersonCircleLineBold ,
  PersonCircleLineRegular ,
  PersonCircleLineThin ,
  PersonFill ,
  PersonLineBold ,
  PersonLineRegular ,
  PersonLineThin ,
  PhoneFill ,
  PhoneLineBold ,
  PhoneLineRegular ,
  PhoneLineThin ,
  PinFill ,
  PinLineBold ,
  PinLineRegular ,
  PinLineThin ,
  PlayFill ,
  PlayLineBold ,
  PlayLineRegular ,
  PlayLineThin ,
  PlusCircleFill ,
  PlusCircleLineBold ,
  PlusCircleLineRegular ,
  PlusCircleLineThin ,
  PlusLineBold ,
  PlusLineRegular ,
  PlusLineThin ,
  PostSquareFill ,
  PostSquareLineBold ,
  PostSquareLineRegular ,
  PostSquareLineThin ,
  RefreshLineBold ,
  RefreshLineRegular ,
  RefreshLineThin ,
  SearchFill ,
  SearchLineBold ,
  SearchLineRegular ,
  SearchLineThin ,
  SeeMoreFill ,
  SeeMoreLineBold ,
  SeeMoreLineRegular ,
  SeeMoreLineThin ,
  SendPlaneFill ,
  SendPlaneLineBold ,
  SendPlaneLineRegular ,
  SendPlaneLineThin ,
  SettingFill ,
  SettingLineBold ,
  SettingLineRegular ,
  SettingLineThin ,
  ShareAndroidFill ,
  ShareAndroidLineBold ,
  ShareAndroidLineRegular ,
  ShareAndroidLineThin ,
  ShareArrowFill ,
  ShareArrowLineBold ,
  ShareArrowLineRegular ,
  ShareArrowLineThin ,
  ShareIosFill ,
  ShareIosLineBold ,
  ShareIosLineRegular ,
  ShareIosLineThin ,
  ThumbUpFill ,
  ThumbUpLineBold ,
  ThumbUpLineRegular ,
  ThumbUpLineThin ,
  TouchFill ,
  TouchLineBold ,
  TouchLineRegular ,
  TouchLineThin ,
  TrashFill ,
  TrashLineBold ,
  TrashLineRegular ,
  TrashLineThin ,
  VideoFill ,
  VideoLineBold ,
  VideoLineRegular ,
  VideoLineThin ,
  WebBold ,
  WebFill ,
  WebRegular ,
  WebThin ,
}
/* No side effect */
