// Generated by ReScript, PLEASE EDIT WITH CARE


var Body = {};

var Headline = {};

var Caption = {};

var $$Text = {
  Body: Body,
  Headline: Headline,
  Caption: Caption
};

export {
  $$Text ,
}
/* No side effect */
