// Generated by ReScript, PLEASE EDIT WITH CARE


var TextVariant = {};

var Body = {};

var Headline = {};

var Caption = {};

var $$Text = {
  TextVariant: TextVariant,
  Body: Body,
  Headline: Headline,
  Caption: Caption
};

export {
  $$Text ,
}
/* No side effect */
