// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Divider(Props) {
  var color = Props.color;
  var thickness = Props.thickness;
  var baseStyle = {
    backgroundColor: color,
    width: "100%"
  };
  var variantStyle = typeof thickness === "number" ? (
      thickness !== 0 ? ({
            height: "10px"
          }) : ({
            height: "1px"
          })
    ) : ({
        height: "" + String(thickness._0) + "px"
      });
  return React.createElement("div", {
              style: Object.assign({}, baseStyle, variantStyle)
            });
}

var make = Divider;

export {
  make ,
}
/* react Not a pure module */
