// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CSF from "../CSF.bs.js";
import * as Divider from "./Divider.bs.js";

var $$default = CSF.make("divider", Divider.make);

Divider.make.args = {
  size: /* Small */0
};

Divider.make.args = {
  size: /* Large */1
};

var dividerStory = Divider.make;

var thin = Divider.make;

var thick = Divider.make;

export {
  $$default ,
  $$default as default,
  dividerStory ,
  thin ,
  thick ,
}
/* default Not a pure module */
