// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CSF from "../CSF.bs.js";
import * as Button from "./Button.bs.js";

var $$default = CSF.make("button", Button.make);

var partial_arg = {
  size: "large",
  label: "large"
};

function large(param) {
  return CSF.makeStory(partial_arg, Button.make, param);
}

var partial_arg$1 = {
  size: "medium",
  label: "medium"
};

function medium(param) {
  return CSF.makeStory(partial_arg$1, Button.make, param);
}

var partial_arg$2 = {
  size: "small",
  label: "small"
};

function small(param) {
  return CSF.makeStory(partial_arg$2, Button.make, param);
}

export {
  $$default ,
  $$default as default,
  large ,
  medium ,
  small ,
}
/* default Not a pure module */
