// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CSF from "../CSF.bs.js";
import * as Button from "./Button.bs.js";

var $$default = CSF.make("button", Button.make);

Button.make.args = {
  size: "large",
  label: "Large"
};

Button.make.args = {
  size: "medium",
  label: "Medium"
};

Button.make.args = {
  size: "small",
  label: "Small"
};

var buttonStory = Button.make;

var large = Button.make;

var medium = Button.make;

var small = Button.make;

export {
  $$default ,
  $$default as default,
  buttonStory ,
  large ,
  medium ,
  small ,
}
/* default Not a pure module */
