// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Button$Button(Props) {
  var label = Props.label;
  return React.createElement("button", undefined, label);
}

var Button = {
  make: Button$Button
};

export {
  Button ,
  
}
/* react Not a pure module */
